# Copyright (c) 2026 Code Infinity
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""ASGI entry point for a Tina4 Python app.

Generated by `tina4 deploy docker --runtime asgi`. Point any ASGI server here:

    uvicorn   asgi:app --workers 4 --host 0.0.0.0 --port 7145
    hypercorn asgi:app --workers 4 --bind 0.0.0.0:7145
    granian   --interface asgi asgi:app --workers 4

asgi() discovers src/routes and THEN returns the callable. Pointing a server
straight at tina4_python.core.server:app starts a working application with no
routes registered - the server boots, /__health answers, and every application
route 404s with nothing in the log to say why.
"""
from tina4_python.core.server import asgi

app = asgi()
