# Tina4 PHP — production Docker image. Generated by `tina4 deploy docker`.
# Two-stage: composer install in a builder, copy the resolved vendor/
# tree into a slim runtime. `TINA4_OVERRIDE_CLIENT=true` lets the
# framework boot without the Rust CLI at runtime.
# The tina4 CLI is installed in EVERY Tina4 image and is the launcher: one
# `tina4 serve --production` across all four languages instead of four
# different per-language entry points. It is a single static musl binary
# copied from a published image -- a layer copy, no toolchain, no compile,
# no network fetch at build time. Override with
# --build-arg TINA4_CLI_IMAGE=... to pin or test a different CLI.
ARG TINA4_CLI_IMAGE=ghcr.io/tina4stack/tina4-cli:v3.8.63
FROM ${TINA4_CLI_IMAGE} AS tina4cli

FROM composer:2 AS deps
WORKDIR /app
COPY composer.json composer.lock* ./
RUN composer install --no-dev --optimize-autoloader --no-scripts

FROM php:8.4-cli-alpine
WORKDIR /app
COPY --from=tina4cli /usr/local/bin/tina4 /usr/local/bin/tina4
# pcntl is NOT optional here, and it is not in the base image.
#
# The built-in server needs it for BOTH of its concurrency modes: forking a
# request so a slow handler cannot block the others, and TINA4_SERVE_WORKERS'
# pre-forked pool. Without pcntl the server silently degrades to ONE process
# handling everything serially - it still answers, so nothing looks broken,
# and every concurrency setting you write in your .env quietly does nothing.
#
# Measured: on stock php:8.4-cli (posix present, pcntl absent) a benchmark of
# fork-per-request, a 4-worker pool and a 16-worker pool produced ONE pid in
# all three cases and identical throughput, because all three were the same
# single-threaded server.
#
# The build FAILS if it does not load, rather than shipping that silence.
RUN install-php-extensions sqlite3 pdo_sqlite opcache pcntl 2>/dev/null \
 || (apk add --no-cache --virtual .build sqlite-dev \
     && docker-php-ext-install pdo_sqlite pcntl \
     && apk del .build)
RUN php -m | grep -qi '^pcntl$' \
 || { echo "pcntl failed to install - the server would run single-process"; exit 1; }
COPY --from=deps /app/vendor /app/vendor
COPY . /app
ENV TINA4_OVERRIDE_CLIENT=true \
    TINA4_DEBUG=false
EXPOSE 7145

# One launcher for all four languages. --host defaults to 0.0.0.0, which is
# required: a server bound to 127.0.0.1 inside a container is unreachable
# through `docker run -p`. --no-browser because there is no browser here.
CMD ["tina4", "serve", "--production", "--no-browser"]
