# Tina4 Ruby — production Docker image. Generated by `tina4 deploy docker`.
# Two-stage: compile gems in a builder that HAS a toolchain, then copy the
# resolved bundle into a slim runtime.
#
# The builder is the full `ruby:3.3` image, not `-slim`: several gems in the
# default dependency set ship native extensions (date, json, nio4r, sqlite3),
# and `-slim` carries no compiler, so `bundle install` dies with
# "Gem::Ext::BuildError: Failed to build gem native extension".
FROM ruby:3.3 AS deps
WORKDIR /app
COPY Gemfile Gemfile.lock* ./
# `deployment true` is deliberately NOT set. It demands a lockfile that matches
# the image's bundler exactly, so a Gemfile.lock generated by a newer bundler on
# the developer's machine hard-fails the build. Installing without it lets
# bundler resolve, and self-upgrade, as needed.
RUN bundle config set --local without 'development test' \
 && bundle config set --local path '/app/vendor/bundle' \
 && bundle install --jobs 4 \
 && rm -rf /app/vendor/bundle/ruby/*/cache

FROM ruby:3.3-slim
WORKDIR /app
# Runtime shared libraries only. The extensions were compiled in the builder but
# still dynamically link against libsqlite3.
RUN apt-get update \
 && apt-get install -y --no-install-recommends libsqlite3-0 \
 && rm -rf /var/lib/apt/lists/*
ENV TINA4_OVERRIDE_CLIENT=true \
    TINA4_DEBUG=false \
    BUNDLE_PATH=/app/vendor/bundle \
    BUNDLE_WITHOUT=development:test
COPY --from=deps /app/vendor /app/vendor
COPY --from=deps /usr/local/bundle /usr/local/bundle
COPY . /app
EXPOSE 7147
CMD ["bundle", "exec", "tina4ruby", "serve", "--production"]
