# Tina4 PHP — production Docker image. Generated by `tina4 deploy docker`.
# Two-stage: composer install in a builder, copy the resolved vendor/
# tree into a slim runtime. `TINA4_OVERRIDE_CLIENT=true` lets the
# framework boot without the Rust CLI at runtime.
FROM composer:2 AS deps
WORKDIR /app
COPY composer.json composer.lock* ./
RUN composer install --no-dev --optimize-autoloader --no-scripts

FROM php:8.4-cli-alpine
WORKDIR /app
RUN install-php-extensions sqlite3 pdo_sqlite opcache 2>/dev/null \
 || (apk add --no-cache --virtual .build sqlite-dev \
     && docker-php-ext-install pdo_sqlite \
     && apk del .build)
COPY --from=deps /app/vendor /app/vendor
COPY . /app
ENV TINA4_OVERRIDE_CLIENT=true \
    TINA4_DEBUG=false
EXPOSE 7145
CMD ["php", "index.php", "0.0.0.0:7145"]
