#!/bin/sh
# Start php-fpm and nginx in one container.
# Generated by `tina4 deploy docker --runtime fpm`.
#
# POSIX sh, not bash: this runs as the container's entry point on images whose
# /bin/sh is dash, where `set -o pipefail`, arrays and /dev/tcp do not exist.
set -eu

# php-fpm goes to the background; nginx is exec'd into PID 1 at the end so that
# docker's signals reach it directly and `docker stop` is a clean shutdown
# rather than a 10-second wait followed by SIGKILL.
php-fpm --daemonize

# Do not exec nginx until php-fpm is actually accepting. Start nginx first and
# every request during the fpm warm-up gets a 502 - and a container answering
# 502 still looks "up" to a naive health check.
#
# The readiness probe is php itself, which is the one thing this image is
# guaranteed to have. `nc` is not installed on php:*-fpm, and /dev/tcp is a
# bash feature that silently does nothing under dash - either would have made
# this loop fall through instantly and defeat its own purpose.
i=0
while [ "$i" -lt 60 ]; do
    if php -r 'exit(@fsockopen("127.0.0.1", 9000, $e, $s, 0.5) ? 0 : 1);' 2>/dev/null; then
        echo "php-fpm is up; starting nginx on :7145"
        exec nginx -g 'daemon off;'
    fi
    i=$((i + 1))
    sleep 0.5
done

echo "php-fpm did not start listening on 127.0.0.1:9000 within 30s" >&2
exit 1
