# Tina4 Ruby — production Docker image. Generated by `tina4 deploy docker`.
# Slim two-stage: bundle install into vendor/bundle, copy into runtime.
FROM ruby:3.3-slim AS deps
WORKDIR /app
COPY Gemfile Gemfile.lock* ./
RUN bundle config set --local deployment 'true' \
 && bundle config set --local without 'development test' \
 && bundle install --jobs 4

FROM ruby:3.3-slim
WORKDIR /app
ENV TINA4_OVERRIDE_CLIENT=true \
    TINA4_DEBUG=false \
    BUNDLE_PATH=/app/vendor/bundle \
    BUNDLE_DEPLOYMENT=true
COPY --from=deps /app/vendor /app/vendor
COPY . /app
EXPOSE 7147
CMD ["bundle", "exec", "tina4ruby", "serve", "--production"]
