#!/bin/sh
# Start the ASGI server named by TINA4_ASGI_SERVER.
# Generated by `tina4 deploy docker --runtime asgi`.
#
# POSIX sh, not bash: this is the container entry point and /bin/sh on the
# python:*-slim images is dash, where `set -o pipefail`, arrays and /dev/tcp do
# not exist - and the last two fail SILENTLY rather than erroring.
set -eu

SERVER="${TINA4_ASGI_SERVER:-uvicorn}"
WORKERS="${TINA4_ASGI_WORKERS:-4}"
HOST="${TINA4_ASGI_HOST:-0.0.0.0}"
PORT="${TINA4_ASGI_PORT:-7145}"

echo "Starting ${SERVER} with ${WORKERS} worker(s) on ${HOST}:${PORT}"

# exec, so the server becomes PID 1 and docker's signals reach it directly.
# Without it every `docker stop` waits the full grace period and then SIGKILLs,
# which turns a clean drain into a hard cut.
case "$SERVER" in
  uvicorn)
    exec uvicorn asgi:app --host "$HOST" --port "$PORT" --workers "$WORKERS"
    ;;
  hypercorn)
    exec hypercorn asgi:app --bind "${HOST}:${PORT}" --workers "$WORKERS"
    ;;
  granian)
    exec granian --interface asgi asgi:app \
         --host "$HOST" --port "$PORT" --workers "$WORKERS"
    ;;
  *)
    echo "Unknown TINA4_ASGI_SERVER: ${SERVER}" >&2
    echo "Supported: uvicorn, hypercorn, granian" >&2
    echo "Any ASGI 3 server works - run it yourself against asgi:app." >&2
    exit 2
    ;;
esac
